### PR TITLE
Add grabber for Basler USB cameras using Pylon

### PR DESCRIPTION
**Pull request by caselitz**
contains some hard-coded values in pylon_grabber.cpp, e.g. image resolution and white balance values
exposure times lower than 1ms cannot be used since they are stored as int representing ms

### CODE REVIEW

**Comment by taketwo** [comment]
Thanks! I'll have a look on Friday.

**Comment by taketwo** [comment]
As I said, can not test, but looks alright! My only request would be to add license at the top of the header/cpp files.

**Comment by caselitz** [comment]
So I copy the license from your grabber files (and add my name after yours)?

Edit: The year should stay 2016 or should it be 2017?

**Comment by taketwo** [comment]
I don't think my name is necessary in your files, I did not contribute :) Year should be the year of creation of the files, i.e. 2017. (You can not claim copyright before the subject to copyright even existed!)

**Comment by taketwo** [comment]
Thanks!

**Pull request merged**
